### ISSUE TITLE
关于反转布局

### ISSUE THREAD

**Issue by yobome** [YerongL/OfficeToolPlus#3]
反转布局
![image](https://user-images.githubusercontent.com/26548120/48042927-ee215d80-e1be-11e8-99ae-598dd7ac84e0.png)
![image](https://user-images.githubusercontent.com/26548120/48042955-085b3b80-e1bf-11e8-8051-3bacbd78a534.png)
反转后和再反转回来还需要改进一下？

**Comment by chiyi4488** [comment]
若你想"快速"得到解答之類的，建議你去telegram群組說一下，因為這裡目前應該只有翻譯工作而已...
或者...等待.....

**Comment by chiyi4488** [comment]
由於作者本人無法回覆，所以這個問題將關閉。
