### ISSUE TITLE
Office2019无法激活

### ISSUE THREAD

**Issue by TheRealMilesLee** [YerongL/OfficeToolPlus#6]
最近在使用OTP工具进行激活的时候发现在软件内显示激活成功，但是进入Office套件里面以后还是报错说未激活。不知是不是OTP的激活码过期还是KMS服务器出了问题。还请尽快解决

感谢！
###################
Recently, when using the OTP tool for activation, it was found that the activation was successful in the software, but after entering the Office suite, it was reported that it was not activated. I wonder if the OTP activation code expired or the KMS server has a problem. Please also resolve as soon as possible

thanks!

**Comment by chiyi4488** [comment]
建議如果不確定的話，可以試著換KMS服務器喔

**Comment by chiyi4488** [comment]
如果在激活頁面中，所有清楚功能都試過之後，還是不行，建議斬草除根，將office全部卸載，並試著用otp內建的清除工具，將剩餘沒有卸載掉的檔案清楚掉，並重新安裝。

如果以前有用過KMS破解等程式，也可以去工具箱頁面中嘗試修復喔

**Comment by chiyi4488** [comment]
> 不知是不是OTP的激活码过期还是KMS服务器出了问题。**还请尽快解决**

若是KMS服務器所出現的問題，請與KMS服務器**提供人**確認，Office Tool 無法修復喔。

另外，此問題若無其它問題，或者已得到解答，請**主動關閉問題**，將在**1禮拜後關閉**。
