### ISSUE TITLE
无法选择安装路径？

### ISSUE THREAD

**Issue by ustbdiego** [YerongL/OfficeToolPlus#7]
如题

**Comment by chiyi4488** [comment]
請提供更多資訊，像是截圖之類的。

**Comment by chiyi4488** [comment]
>如题

>請提供更多資訊，像是截圖之類的。

抱歉，剛剛查詢了一下，似乎Office Tool Plus (Lite)是無法選擇安裝路徑的，這或許是微軟所做的限制。
如果是下載 or 來源路徑，即可修改，Plus 可以至可選設置-->安裝設置 進行修改。
Lite 即在安裝頁面中。
如果我誤會題目，還請你多多解釋，是有"安裝路徑"功能，但無法修改。
還是不確定是否有"安裝路徑"功能。

**Comment by chiyi4488** [comment]
**此問題已解決**，若你認為並沒有回答道你的問題，請提出**重新開啟**問題。
你也可以到 _群組_ 中詢問(_Telegram_,_QQ_)，或許會有更棒的解答。(當然也可以在這裡問:))
